name: Run URL parser CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build images
    strategy:
      fail-fast: false
      matrix:
        include:
          - kind: script
          - kind: daemon

    steps:
      - uses: actions/checkout@v4

      - name: "Modify script according to purpose: ${{ matrix.kind }}"
        if: matrix.kind == 'daemon'
        run: |
          cat daemon_snippet.txt >> main.py

      - name: Build image
        run: |
          IMAGE_TAG="url-parser:latest-${{ matrix.kind }}"
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Save image to tar
        run: |
          TARBALL_NAME="url-parser-${{ matrix.kind }}.tar"
          docker save ${{ env.IMAGE_TAG }} > $TARBALL_NAME
          echo "TARBALL_NAME=$TARBALL_NAME" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
          input: ${{ env.TARBALL_NAME }}
          severity: 'CRITICAL,HIGH'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARBALL_NAME }}
          path: ${{ env.TARBALL_NAME }}

  run:
    runs-on: ubuntu-latest
    name: Run images
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: url-parser-script.tar
          path: .

      - name: Load image
        run: docker load -i url-parser-script.tar

      - name: Run image in stdout mode
        run: |
          docker run url-parser:latest-script \
            -u https://youtube.com \
            -u https://google.com \
            -u https://news.ycombinator.com \
            -u https://arstechnica.com \
            -o stdout

      - name: Run image in json mode
        run: |
          docker run url-parser:latest-script \
            -u https://youtube.com \
            -u https://google.com \
            -u https://news.ycombinator.com \
            -u https://arstechnica.com \
            -o json | jq

