name: Run URL parser CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - kind: script
          - kind: daemon

    steps:
      - uses: actions/checkout@v4


      - name: Modify script
        if: matrix.kind == 'daemon'
        run: |
          cat daemon_snippet.txt >> main.py

      - name: Build image
        run: |
          IMAGE_TAG="url-parser:latest-${{ matrix.kind }}"
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Save image to tar
        run: docker save ${{ env.IMAGE_TAG }} > url-parser-${{ matrix.kind }}.tar

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
          input: url-parser-${{ matrix.kind }}.tar
          severity: 'CRITICAL,HIGH'

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_TAG }}
          path: "*.tar"
